### PR TITLE
[nrf temphack] Revert "modules: tfm: cleanup redundant Kconfig...

### PR DESCRIPTION
**Pull request by hakonfam**
... symbol selection"

This reverts commit 0924cb55df52bcf40dc3e0791fa59a13982aa164.

Ref: NCSDK-7591

Signed-off-by: Håkon Øye Amundsen <haakon.amundsen@nordicsemi.no>

### CODE REVIEW

**Review by oyvindronningstad — APPROVED** [review]

**Comment by oyvindronningstad** [comment]
cc @ioannisg

**Comment by de-nordic** [comment]
Seems to fix the compilation problems.

**Comment by ioannisg** [comment]
@oyvindronningstad could you explain why this needs to be reverted? It's working upstream

**Comment by oyvindronningstad** [comment]
Because the upstream samples override certain weak functions (tfm_ns_interface_dispatch and tfm_ns_interface_init). Reverting this commit allows TFM to be added to any sample without having to copy those functions. Eventually we want to add the functions automatically whenever TFM is enabled. I have this on a branch but it's not ready yet.

**Pull request merged**
